export const PermissionName={
    user:"user_Permission_CRUD",
    userManagement:"user_Management_CRUD",
    reportDoor:"report_door_R",
    reportEmployee:"report_member_R",
    reportDoorGroup:"report_doorgroup_R",
    reportCard:"report_card_R",
    reportContractor:"report_contractor_R",
    reportDemographic:"report_demographic_R",
    reportAttendance:"report_attendance_R",
    reportVisitor:"report_visitor_R",
    permissionTable:"door_permissiontable_CRUD",
    member:"door_member_CRUD",
    doorgroup:"door_doorgroup_CRUD",
    door:"door_door_CRUD",
    reader:"door_reader_CRUD",
    elevatorgroup:"door_elevatorgroup_CRUD",
    elevator:"door_elevator_CRUD",
    floor:"door_floor_CRUD",
    floorgroup:"door_floorgroup_CRUD",
    syncreceiver:"notification_sync_CRUD",
    accessLevel:"door_accesslevel_CRUD",
    humanResource:"system_hurmanresource_CRUD",
    systemLicense:"system_license_CRUD",
    operationLog:"system_operationlog_R"
};
export const PermissionList = [
    {key:PermissionName.accessLevel, route :"", group:"AccessLevel", access:{C:false,R:false,U:false,D:false}},
    {key:PermissionName.member, route :"/member", group:"AccessLevel", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.permissionTable, route :"/permissiontable", group:"AccessLevel", access:{C:true,R:true,U:true,D:true}},

    {key:PermissionName.reportEmployee, route :"/employeereport", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportDoor, route :"/doorreport", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportDoorGroup, route :"/doorgroupreport", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportCard, route :"/cardreport", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportContractor, route :"/contractorreport", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportDemographic, route :"/demographicreport", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportAttendance, route :"/attendance", group:"Report", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.reportVisitor, route :"/visitorreport", group:"Report", access:{C:false,R:true,U:false,D:false}},    

    {key:PermissionName.door, route :"/door", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.doorgroup, route :"/doorgroup", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.floor, route :"/floor", group:"Setting", access:{C:false,R:true,U:false,D:false}},
    {key:PermissionName.floorgroup, route :"/floorgroup", group:"Setting", access:{C:true,R:true,U:true,D:true}},    
    {key:PermissionName.elevatorgroup, route :"/elevatorgroup", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.elevator, route :"/elevator", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.reader, route :"/reader", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.syncreceiver, route :"/syncreceiver", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.humanResource, route :"", group:"Setting", access:{C:false,R:false,U:false,D:false}},
    {key:PermissionName.systemLicense, route :"/license", group:"Setting", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.operationLog, route :"", group:"Setting", access:{C:false,R:true,U:false,D:false}},

    {key:PermissionName.user, route :"/userpermission", group:"Permission", access:{C:true,R:true,U:true,D:true}},
    {key:PermissionName.userManagement, route :"/user", group:"Permission", access:{C:true,R:true,U:true,D:true}}
    
];